export const ADD_ITEM="ADD-ITEM";
export const REMOVE_ITEM="REMOVE-ITEM";
export const AUCTION_INIT_SUCCESS="AUCTION-INIT-SUCCESS";
export const AUCTION_INIT_FAILED="AUCTION-INIT-FAILED";
export const GET_ITEM_SUCCESS="GET-ITEM-SUCCESS";
export const GET_ITEM_FAILED="GET-ITEM-FAILED";
export const CLEAR_ITEM_STATE="CLEAR_ITEM_STATE";