export const ADD_ITEM="ADD-ITEM";
export const REMOVE_ITEM="REMOVE-ITEM";
export const AUCTION_INIT_SUCCESS="AUCTION-INIT-SUCCESS";
export const AUCTION_INIT_FAILED="AUCTION-INIT-FAILED";
export const GET_ITEM_SUCCESS="GET-ITEM-SUCCESS";
export const GET_ITEM_FAILED="GET-ITEM-FAILED";
export const CLEAR_ITEM_STATE="CLEAR_ITEM_STATE";

export const ADD_ITEM_SUCCESS="ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILED= "ADD_ITEM_FAILED"; 
export const EDIT_ITEM_SUCCESS="EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAILED="EDIT_ITEM_FAILED";
export const DELETE_ITEM_SUCCESS="DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILED="DELETE_ITEM_FAILED";


export const ADD_BID_SUCCESS="ADD-BID-SUCCESS";
export const ADD_BID_FAILED="ADD-BID-FAILED";